name: Play

on:
  push:
  pull_request:

jobs:
  play:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.5-dind
        ports:
          - 2375:2375
        volumes:
          - certs:/certs

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump Env context
        run: env
      - run: docker version && docker build -t test .
      - uses: docker://docker:latest
        with:
          entrypoint: sh
          args: -c "docker version && docker build -t test2 ."
      - uses: docker://docker:latest
        with:
          entrypoint: sh
          args: -c "docker images && docker ps"

  play2:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      volumes: certs:/certs

    services:
      docker:
        image: docker:19.03.5-dind
        ports:
          - 2375:2375
        volumes:
          - certs:/certs

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump Env context
        run: env
      - run: docker version && docker build -t test .
