name: Play

on:
  push:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container: node:12
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: My action
        uses: ./ # Uses an action in the root directory
        with:
          name: "awesome"
