name: Play

on:
  push:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    # container: node:12
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install && yarn run build
      - run: ls -la
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git commit -m "Add changes" -a
          repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          echo $repo
          git push "${repo}" HEAD:${{ github.ref }}
      - name: My action
        uses: ./ # Uses an action in the root directory
        with:
          name: "awesome"
