name: Play

on:
  push:

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/sonar-scanner-action@26ba11cbe6061fd36800368a8a760e33309ab5e8
        id: sonar
        with:
          token: 1234
          projectName: My Project Name
          projectKey: project.key.from.sonar.qube
          url: https://your.sonar.instance.io/
          enablePullRequestDecoration: true
          onlyConfig: true
      - name: sonar config
        run: echo "Config ${{ steps.sonar.outputs.sonarParamters }}"
