name: Play

on:
  push:

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/sonar-scanner-action@55ec6690c3640998a34ea016eca4389ee45ac0a6
        id: sonar
        with:
          token: 1234
          projectName: My Project Name
          projectKey: project.key.from.sonar.qube
          url: https://your.sonar.instance.io/
          enablePullRequestDecoration: true
          onlyConfig: true
      - name: sonar config
        run: echo "Config ${{ steps.sonar.outputs.sonarParamters }}"
